<?php

/**
 * php-dna.
 *
 * tools for genetic genealogy and the analysis of consumer DNA test results
 *
 * @author          Devmanateam <devmanateam@outlook.com>
 * @copyright       Copyright (c) 2020-2023, Devmanateam
 * @license         MIT
 *
 * @link            http://github.com/familytree365/php-dna
 */

namespace Dna;

/**
 * Class Resources.
 */
class Resources extends \Dna\Snps\SNPsResources
{

  protected $_genetic_map = '{}';
  protected $_genetic_map_name = '';
  protected $_cytoBand_hg19 = [];
  protected $_knownGene_hg19 = [];
  protected $_kgXref_hg19 = [];

  public function __construct($resources_dir = 'resources')
    {
      parent::__construct($resources_dir = $resources_dir);
    }

  public function get_genetic_map_HapMapII_GRCh37() {
      // Get International HapMap Consortium HapMap Phase II genetic map for Build 37.
      // References:
      // - International HapMap Consortium (2007). A second generation human haplotype map of over 3.1 million SNPs. Nature 449: 851-861.
      // - The map was generated by lifting the HapMap Phase II genetic map from build 35 to GRCh37.
      // - The original map was generated using LDhat as described in the 2007 HapMap paper (Nature, 18th Sept 2007).
      // - The conversion from b35 to GRCh37 was achieved using the UCSC liftOver tool. Adam Auton, 08/12/2010

      if ($this->_genetic_map_name != "HapMap2") {
          // $this->_genetic_map = $this->_load_genetic_map_HapMapII_GRCh37(
          //     $this->_get_path_genetic_map_HapMapII_GRCh37()
          // );
          $this->_genetic_map_name = "HapMap2";
      }

      return $this->_genetic_map;
  }

}
